### ISSUE TITLE
Ensuring that users add "http://" when accessing the server

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri-docs#129]
It's not always clear to users in the documentation that "http://" must be included in the URL when accessing Kolibri via server. https://kolibri.readthedocs.io/en/latest/access.html#access-kolibri 

We've also seen before where people assume it's "https" so this could be helpful for addressing that as well. 

Suggestion to add a "tip" to the documentation.

**Comment by benjaoming** [comment]
@laurenlichtman could you elaborate the type of wrong entries?

It's because it's hard to know which terms that browsers choose to redirect to Google searches. It may differ.

Entering a valid IP address (`1.2.3.4`) would usually be valid as a URL, hence not redirected as a Google search and adding the `http://` implicitly. Adding the port `1.2.3.4:5678` also works.

So interested in hearing about when this doesn't work..

**Comment by laurenlichtman** [comment]
@lauradanforth experienced this issue with an older OS during training in Uganda where only the IP was entered without "http://" and the clients could not connect to the server.

**Comment by benjaoming** [comment]
Thanks!

**Comment by jredrejo** [comment]
Current browsers tend to use `https://` instead of `http://` as default, unless the port is entered. In our case this should not give any problem as the kolibri usually requires adding the :port . Maybe we should mention in the documentation that moving kolibri to port 80 will force the users to write always `http://` or the browser won't find the server.

**Comment by benjaoming** [comment]
@jredrejo yeah, that could be quite confusing -- especially also thinking about the login page already suffering from "not safe" kind of warnings (because of missing SSL on a page with a `password` input field). I'm not sure if the automatic use of `https` is done through an automatic probe on a server's 443 port or not.

**Comment by jredrejo** [comment]
@benjaoming yeah, so, thinking of solving this issue: we can't control what browsers set as default. I would say that the only possible solution on our side is adding a note to the docs saying that in case you use port 80 you must ensure to advice your users to type `http://`
what do you think?

**Comment by benjaoming** [comment]
Yes, agreed, can you implement this?

I really liked your comment because it reminded us that we ALSO have to anticipate more issues given that the login form is non-SSL. Let's look into that separately and gather some screenshots of the behavior.
