### ISSUE TITLE
Document options.ini usage

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri-docs#22]
For advanced users, we should document how to use the options.ini file for Kolibri.

The exact form this documentation should take is unclear, as it may depend on how we end up deciding to template the options.ini file.

Ref: https://github.com/learningequality/kolibri/pull/3607

**Comment by radinamatic** [comment]
Lot of stuff in the original PR... 🤔 

If this is something that should go into the [0.10 docs update](https://github.com/learningequality/kolibri-docs/pull/28), I would need a list of high level commands and options to test first, in order to write proper instructions.

Working with command line is "buried" at the [end of the `Manage` chapter of the user docs](http://kolibri.readthedocs.io/en/latest/manage.html#working-with-kolibri-from-the-command-line).

**Comment by indirectlylit** [comment]
I don't think it's critical to document it immediately (for 0.10.0). Initially it's going to be helpful for internal use and and in close collaboration with partners. We can take some time making sure that the public documentation is clear and best practices are laid out.

**Comment by radinamatic** [comment]
Ok, if it's for internal use for starters, maybe it could go to developer docs at the beginning, and I can make a user doc version afterwards?

**Comment by indirectlylit** [comment]
>  Ok, if it's for internal use for starters, maybe it could go to developer docs at the beginning, and I can make a user doc version afterwards?

That sounds like the right move to me.

Related: in https://github.com/learningequality/kolibri/pull/3736 @jredrejo added a bunch of new options. It's not totally clear to me that we _want_ this many options, or if we do have them, that we'd want them all to be officially-supported. I think we may need a way to distinguish stable, supported options from internal, experimental ones

**Comment by benjaoming** [comment]
> It's not totally clear to me that we want this many options, or if we do have them, that we'd want them all to be officially-supported.

Yes, these options added are valuable, because advanced users need a way to tweak Kolibri to perform better according to the hardware they have, or the system resources needed to be freed for other running processes.

The steps ahead are more about creating a UI (control panel for these).

I made a comment in the PR about the .ini section -- maybe that's a good place to be aware and manage the threat of options clutter.

**Comment by radinamatic** [comment]
This has been documented since release 0.11:

https://kolibri.readthedocs.io/en/latest/manage.html#customize-kolibri-settings-with-the-options-ini-file

Please open new issues for additional options to include.
