### ISSUE TITLE
in case of reports, add note about malformed databases

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#29]
If users contact us with reports of malformed DBs, let's add a note somewhere that if someone sees this uncommon error, they should contact us on the forums for help recovering their data:

```
sqlite3.DatabaseError: database disk image is malformed
```

**Comment by benjaoming** [comment]
@indirectlylit this already fires if you run Kolibri with a malformed DB:

```
$ kolibri start
WARNING:root:No C Extensions available for this platform.

ERROR    
Your database is corrupted. This is a known issue that is usually fixed by running this command: 

    sqlite3 /home/benjamin/.kolibri/db.sqlite3 .dump | sqlite3 fixed.db 
    cp fixed.db /home/benjamin/.kolibri/db.sqlite3

Notice that you need the 'sqlite3' command available on your system prior to running this.


ERROR:kolibri.utils.cli:
Your database is corrupted. This is a known issue that is usually fixed by running this command: 

    sqlite3 /home/benjamin/.kolibri/db.sqlite3 .dump | sqlite3 fixed.db 
    cp fixed.db /home/benjamin/.kolibri/db.sqlite3

Notice that you need the 'sqlite3' command available on your system prior to running this.

```

**Comment by benjaoming** [comment]
Thanks for pinning this - I guess let's leave this issue open, and if we don't hear any user-related issues about malformed dbs in the next months time, we can close this issue... and suspect that the CLI error message was sufficient or people don't have malformed dbs :)

**Comment by indirectlylit** [comment]
Ah, I misunderstood what you wanted when you said 

> In case support questions appear from users, lets add a "known issues" chapter in the docs? Something where the work-around for a "malformed" database can appear?

I'll rename the issue

**Comment by radinamatic** [comment]
So the workaround steps for malformed database that need to be documented are the one from above output?
```
sqlite3 /home/<your_username>/.kolibri/db.sqlite3 .dump | sqlite3 fixed.db 
cp fixed.db /home/<your_username>/.kolibri/db.sqlite3
```

What if user does not have the `sqlite3` command available? Did someone manage to malform the db on a Windows system?

I'm not sure I like the idea of a `Known issues` chapter just for this... Let's leave aside the custom to put "known" issues in the release notes, working under the assumption that not that many users actually read those. Since the recommendation to ask on the community forums is already at the very top of the currently existing [Support and Troubleshooting](http://kolibri.readthedocs.io/en/latest/manage.html#support) chapter, for all and any problems/questions users may have, I could add the issue and the above steps as an item inside that chapter.

**Comment by benjaoming** [comment]
> What if user does not have the sqlite3 command available? Did someone manage to malform the db on a Windows system?

I don't know, I also don't have any recipe for Windows at hand. That's why I didn't write anything about how to install it.

> I'm not sure I like the idea of a Known issues chapter just for this... Let's leave aside the custom to put "known" issues in the release notes, working under the assumption that not that many users actually read those.

It's very normal to have such areas of documentation and release notes. At best, people read it before asking questions, at worst, it just means that we can easily refer to answers.

**Comment by radinamatic** [comment]
Added as the *[DB troubleshooting](https://github.com/learningequality/kolibri-docs/pull/28/commits/88e4599a02894ff3286a75ce141978c6dd8d17e3)* section! 👍
