### ISSUE TITLE
research possible additions to FAQ, and audit existing

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-docs#31]
We should research if there are additional tips that might help end-users set up and use Kolibri. We should also audit the existing questions to ensure they actually belong.

For example, [see suggestions here](https://github.com/learningequality/kolibri-installer-debian/pull/43#issuecomment-401443285) related to USB issues like:

- Write mode
- Inconsistent or broken devices
- Inconsistent or broken data

Before adding new tips, let's make sure that "frequently asked questions" are actually asked frequently. This can be determined based on the Clearinghouse, forums, github issues, and internal questions asked within LE on Slack.

Recommend that we avoid adding tips and notes for which there's no evidence that people are having issues, because this makes it more difficult for users to find answers to questions they are more likely to have.

**Comment by benjaoming** [comment]
Copying in my FAQ suggestion...

     

## Problems importing and exporting with USB devices

Kolibri needs read and write access to your USB devices.

**User account access:** Running Kolibri from a normal desktop instance of your operating system is safe, but if you have either: 1) Installed Kolibri in your own environment running as a non-desktop user (for instance UWSGI) or b) you have upgraded Kolibri on Debian from a version <0.10, then you can follow [these instructions](https://learningequality.org/r/docs-debian-change-user) to move Kolibri from one system user account to another. In order to grant access to USB devices for other accounts, we refer to the documentation of your operating system.

**Write mode:** Some USB devices will experience problems when they are unplugged from the computer in an "unclean" way. If you are denied access to write to the device, look for options to "fix" or "repair" the file system.

**Inconsistent or broken devices:** It will happen that SD storage "expires". So always keep your receipts! When reading and writing content data of many gigabytes, there is an increased chance that you will discover the limits of the device's quality.

**Inconsistent or broken data:** Copying data can take a long time. If you do not see a final success message after the copy is done, do not assume that the data has been imported/exported correctly. Instead, start over. Otherwise you risk inconsistent and malfunctioning content data.

**Comment by radinamatic** [comment]
Added to the 0.10 docs updates, alongside other *troubleshoot* recommendations:

https://github.com/learningequality/kolibri-docs/pull/28/files#diff-5f783e99ad465665334f124ff64d1627R81

**Comment by indirectlylit** [comment]
good solution, thanks
