### ISSUE TITLE
Very light custom styling

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-docs#56]
With inspiration from here, we can tweak the theme a little bit with LE/Kolibri colors using simple CSS.

`https://github.com/wagtail/wagtail/issues/4081`

**Comment by radinamatic** [comment]
I've already added more small changes in the CSS in my [latest update PR](https://github.com/learningequality/kolibri-docs/pull/54/files#diff-5d671d7742518690c10c7922399b60ab), we could build up on that!

**Comment by radinamatic** [comment]
This would be the test of using the Kolibri logo blue (#00AEF0), instead of the default RTD one:

![ledev18aut start running - oracle vm virtualbox_113](https://user-images.githubusercontent.com/1457929/47629564-16b0b400-db3c-11e8-93ee-89e2474fa6a1.png)

![ledev18aut start running - oracle vm virtualbox_112](https://user-images.githubusercontent.com/1457929/47629531-eec15080-db3b-11e8-82f1-90a7f5fe5126.png)

**Comment by radinamatic** [comment]
I thought the Kolibri purple would be too dark, but it actually looks quite nice :heart: 

![ledev18aut start running - oracle vm virtualbox_116](https://user-images.githubusercontent.com/1457929/47644469-82137980-db6e-11e8-8248-3635b0b37c2d.png)

cc @indirectlylit @jtamiace @khangmach

**Comment by benjaoming** [comment]
Yup, I think we should go with that @radinamatic - thanks for trying it out!

It gives the documentation its own touch, while not being a super-complicated theming maneuver.

The Kolibri blue conflicted with remaining theme's blue color, so would require more adjustments.
