### ISSUE TITLE
Fix up basic command line instructions

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-docs#66]
Proposing to improve the guide for users to use the command line...

1. It shouldn't be a Warning box
1. Clarify Windows instructions more, perhaps with a screenshot or using the `WIN+R` shotcut.. I think this part is very hard to understand, also it assumes drive letter `C:`.
   > In Windows you need to open cmd.exe Command prompt in the folder where Kolibri executable is located: c:/Python34/Scripts.
1. I don't think that `python kolibri start` works on MacOS, but maybe `python -m kolibri start` will? It also lacks an instruction on how to start the command line (I think Spotlight + type "Terminal", not sure)
1. Remove the .PEX instructions entirely.
1. Also remove the last part
   > Make sure not to include the angle brackets “< >” in the commands below.*

![image](https://user-images.githubusercontent.com/374612/52919867-026d0e80-3307-11e9-9c78-d67719ff27dc.png)

**Comment by radinamatic** [comment]
1. While technically *not* a warning, a `Note` box did not seem incisive enough to me. If you have an alternative, I'll be happy to hear!

2.   `screenshot or using the WIN+R shortcut` - Good suggestion, will be added!

3. Noted, will correct!

4. Not sure why you are suggesting to eliminate these completely. Some users still need to use PEX, and if they need to use any of the commands in question, this is the only way to do it that I'm aware of... :thinking: 

5. That warning is because we had users including the brackets in the commands, probably because they were copying and pasting directly.

**Comment by indirectlylit** [comment]
couple ideas, feel free to take or leave:

.1. Perhaps just make it a new sub-section, sibling of "Start/Stop Kolibri"? Could call it "Tips for Working from the Command Line" or something

.5. The warning seems reasonable to me but there seems to be an extraneous asterisk: ![image](https://user-images.githubusercontent.com/2367265/53099544-defabd00-34da-11e9-9548-af4bee297d48.png)
